"use client";

import { useMemo, useState } from "react";

function escapeJsonString(input: string, normalizeNewlines: boolean) {
  // Escape into a JSON string literal body.
  // Note: JSON strings MUST escape real newlines. JSON.stringify will emit "\\n".
  const escapedBody = JSON.stringify(input).slice(1, -1);

  // If you don't want to see "\\n" in the escaped output, strip the escape sequences.
  // This changes the meaning (newlines are lost), but matches the UX expectation for
  // "make it one line" copy/paste.
  if (normalizeNewlines) {
    return escapedBody
      // remove escaped newlines generated by JSON.stringify
      .replace(/\\r\\n/g, "")
      .replace(/\\r/g, "")
      .replace(/\\n/g, "")
      // in case input already contained literal CR/LF (rare), also remove real ones
      .replace(/\r\n|\r|\n/g, "");
  }

  return escapedBody;
}

function unescapeJsonString(input: string) {
  // Accept either:
  // 1) A quoted JSON string literal: "{\"a\":1}"
  // 2) An unquoted escaped body: {\"a\":1}
  // 3) A JSON object/array text that contains escaped quotes: { \"a\": 1 }
  const trimmed = input.trim();
  if (!trimmed) return "";

  // Case 3: user pasted something that looks like JSON object/array, but keys/strings are written as \"...\".
  // Example: {  \"hello\": \"world\" }
  // We can safely unescape the quote characters and then parse as JSON.
  if (
    (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
    (trimmed.startsWith("[") && trimmed.endsWith("]"))
  ) {
    const maybeJson = trimmed.replace(/\\"/g, '"');
    try {
      const obj = JSON.parse(maybeJson);
      return JSON.stringify(obj, null, 2);
    } catch {
      // If it still isn't valid JSON, fall back to generic unescape-as-string behavior.
    }
  }

  // Case 1: parse directly (works for quoted JSON string literals)
  try {
    const direct = JSON.parse(trimmed);
    if (typeof direct === "string") return direct;
  } catch {
    // fall through
  }

  // Case 2: treat it as an escaped body and wrap it as a JSON string
  const asJsonLiteral = `"${trimmed.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
  return JSON.parse(asJsonLiteral) as string;
}

export default function JsonStringEscape() {
  const [raw, setRaw] = useState<string>("");
  const [mode, setMode] = useState<"escape" | "unescape">("escape");
  const [normalizeNewlines, setNormalizeNewlines] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);

  const computed = useMemo((): { result: string; error: string } => {
    if (!raw) return { result: "", error: "" };

    try {
      const out =
        mode === "escape" ? escapeJsonString(raw, normalizeNewlines) : unescapeJsonString(raw);
      return { result: out, error: "" };
    } catch {
      return {
        result: "",
        error:
          mode === "escape"
            ? "转义失败"
            : "去转义失败：请输入 JSON 字符串（带外层引号）或转义后的正文（不带外层引号）",
      };
    }
  }, [raw, mode, normalizeNewlines]);

  const handleCopy = async () => {
    if (!computed.result) return;
    try {
      await navigator.clipboard.writeText(computed.result);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch (e) {
      console.error("copy failed", e);
    }
  };

  const clear = () => {
    setRaw("");
    setCopied(false);
  };

  return (
    <div className="w-full max-w-4xl space-y-4 mx-auto">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">JSON String 转义 / 去转义</h1>
          <p className="text-sm text-gray-500">
            把一段文本转成 JSON 字符串可用的转义形式（escape），或把带转义的 JSON 字符串还原成原文（unescape）
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            disabled={!computed.result}
            className="rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 disabled:cursor-not-allowed disabled:text-gray-400"
          >
            {copied ? "已复制" : "复制结果"}
          </button>
          <button
            type="button"
            onClick={clear}
            className="rounded border border-gray-200 bg-gray-100 px-3 py-2 text-sm text-gray-700 hover:bg-gray-200"
          >
            清空
          </button>
        </div>
      </div>

      <div className="rounded border border-black/10 dark:border-white/20 bg-white dark:bg-neutral-900 p-4 space-y-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-3">
            <span className="text-sm text-gray-600 dark:text-gray-300">模式</span>
            <select
              value={mode}
              onChange={(e) => {
                setMode(e.target.value as "escape" | "unescape");
                setCopied(false);
              }}
              className="w-40 rounded border border-gray-300 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="escape">转义 (escape)</option>
              <option value="unescape">去转义 (unescape)</option>
            </select>
          </div>

          {mode === "escape" ? (
            <label className="flex items-center gap-2 text-xs text-gray-500 select-none">
              <input
                type="checkbox"
                checked={normalizeNewlines}
                onChange={(e) => {
                  setNormalizeNewlines(e.target.checked);
                  setCopied(false);
                }}
              />
              去掉换行（不输出 \\n）
            </label>
          ) : (
            <div className="text-xs text-gray-500">支持带或不带外层双引号</div>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <div className="text-sm font-medium text-gray-700 dark:text-gray-200">输入</div>
            <textarea
              value={raw}
              onChange={(e) => {
                setRaw(e.target.value);
                setCopied(false);
              }}
              placeholder={
                mode === "escape"
                  ? "输入原始文本（可包含换行/引号等）"
                  : "输入带转义的内容，例如 {\\\"a\\\":1} 或 \"{\\\"a\\\":1}\""
              }
              className="w-full h-56 p-3 rounded border border-black/10 dark:border-white/20 bg-white dark:bg-neutral-900 font-mono text-sm"
            />
          </div>

          <div className="space-y-2">
            <div className="text-sm font-medium text-gray-700 dark:text-gray-200">输出</div>
            <textarea
              value={computed.result}
              readOnly
              placeholder="结果将在这里显示"
              className="w-full h-56 p-3 rounded border border-black/10 dark:border-white/20 bg-neutral-50 dark:bg-neutral-950 font-mono text-sm"
            />
          </div>
        </div>

        {computed.error ? <div className="text-sm text-red-600">{computed.error}</div> : null}
      </div>
    </div>
  );
}
